[project]
name = "agent"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "google-adk>=1.11.0",
    "litellm>=1.75.8",
    "pathlib>=1.0.1",
    "pydantic>=2.11.7",
    "uuid>=1.30",
]
